<?php
namespace app\index\controller;

use think\Config;
use think\Controller;
use think\captcha\Captcha;
use think\Request;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(isMobile()){
           $this->redirect('mobile/index');
        }
        $this->is_login();
    }

    /**
     * 系统验证码
     */
   public  function verify()
    {
        $config =    [
            // 验证码字体大小
            'fontSize'    =>    30,
            // 验证码位数
            'length'      =>    3,
            // 关闭验证码杂点
            'useNoise'    =>    false,
        ];
        $captcha = new Captcha($config);
        return $captcha->entry();

    }



    /**
     * 检测用户是否登录
     */
    public function is_login()
    {
     return true;
    }

}