<?php
namespace app\index\controller;

use think\Config;
use think\Controller;

class Mobile extends Controller
{
    //pc 端控制
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(!isMobile()){
            $this->redirect('index/index');
        }
    }

    public function index()
    {
        return $this->fetch();
    }

    public function buy()
    {
        return $this->fetch();
    }

    public function orderinfo()
    {
        return $this->fetch();
    }

    public function search()
    {
        return $this->fetch();
    }

    public function sdfahuo()
    {
        return $this->fetch();
    }

    public function trade()
    {
        return $this->fetch();
    }

    public function zdfahuo()
    {
        return $this->fetch();
    }

}